name: Exploring Vairables and Secrets
on: 
    push:


jobs: 
    testing:
        strategy: 
            matrix: 
                os: [ubuntu-latest, windows-latest, ubuntu-22.04 ] 
                image: [hello-world, debian ]
                exclude: 
                - os: windows-latest
                  image: debian 
                include: 
                - os: ubuntu-22.04
                  image: amd64/alpine
        runs-on: "${{ matrix.os }}"
        steps: 
            - run: docker run  ${{ matrix.image }}
